from Main.views.EnterView import EnterView
from Main.views.MainView import MainView
from Main.views.TasksView import TasksView
from Main.views.AccountView import AccountView
from Main.views.ExitView import ExitView
from Main.views.TaskSettingsView import TaskSettingsView
from Main.views.RatingView import RatingView
from Main.views.SetsView import SetsView
from Main.views.TaskView import TaskView
from Main.views.SolutionsTableView import SolutionsTableView
from Main.views.TaskRuntimeView import TaskRuntimeView
from Main.views.SolutionView import SolutionView
from Main.views.ImageView import ImageView
from Main.views.SendCodeView import SendCodeView
from Main.views.SetSettingsView import SetSettingsView
from Main.views.SolutionsView import SolutionsView
from Main.views.SetView import SetView
from Main.views.GroupView import GroupView
from Main.views.CheckersView import CheckersView
from Main.views.ChatsView import ChatsView
from Main.views.DownloadFileView import DownloadFileView
from Main.views.social import *
