stages:
  - build
  - deploy-dev
  - deploy-prod

variables:
  SOLUTIONS_ROOT_EXTERNAL: "/sprint-data/data/solutions"
  DB_HOST: "postgres"

build:
  stage: build
  tags:
    - main
  script:
    - docker login -u mathwave -p Fuck0ffb1tch
    - docker build -t mathwave/sprint-repo:sprint .
    - docker push mathwave/sprint-repo:sprint

.deploy:
  script:
    - docker login -u mathwave -p Fuck0ffb1tch
    - docker pull mathwave/sprint-repo:sprint
    - docker-compose up -d

deploy-dev:
  extends:
    - .deploy
  stage: deploy-dev
  tags:
    - main
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: manual
  variables:
    PORT: 80

deploy-prod:
  extends:
    - .deploy
  stage: deploy-prod
  tags:
    - prod
  only:
    - master
  when: manual
  variables:
    PORT: 443
