stages:
  - build
  - deploy

before_script:
  - echo "Starting..."
  - docker info

after_script:
  - echo "Done!"

build:
  stage: build
  tags:
    - main
  script:
    - docker build -t sprint .

deploy:
  stage: deploy
  tags:
    - main
  script:
   - docker-compose up -d
