stages:
  - build
  - deploy-dev
  - deploy-prod

before_script:
  - echo "Starting..."
  - docker info

after_script:
  - echo "Done!"

build:
  stage: build
  tags:
    - main
  script:
    - docker build -t sprint .

deploy-dev:
  stage: deploy-dev
  tags:
    - main
  variables:
    PORT: 80
  script:
   - docker-compose up -d

deploy-prod:
  stage: deploy-prod
  tags:
    - prod
  only:
    - master
  when: manual
  variables:
    PORT: 443
  script:
    - docker-compose up -d
