stages:
  - build
  - deploy

before_script:
  - echo "Starting..."

after_script:
  - echo "Done!"

build:
  stage: build
  script:
    - docker build -t sprint .

deploy:
  stage: deploy
  script:
   - docker-compose up -d
