version: "3"


services:

  postgres:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: sprint
    volumes:
      - /sprint-data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: mathwave/sprint-repo:sprint
    restart: always
    environment:
      PORT: $PORT
<<<<<<< HEAD
      DB_HOST: $DB_HOST
      RABBIT_HOST: $RABBIT_HOST
      FS_HOST: $FS_HOST
=======
      HOST: $HOST
>>>>>>> a512261c4d4b443cf25874181acd50485f1b40a4
    command: scripts/runserver.sh
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /sprint-data/media:/usr/src/app/media
    depends_on:
      - postgres
      - rabbitmq
      - storage

  storage:
    restart: always
    image: mathwave/sprint-repo:sprint
    command: python manage.py storage
    ports:
      - "5555:5555"
    volumes:
      - /sprint-data/data:/usr/src/app/data

  bot:
    image: mathwave/sprint-repo:sprint
    restart: always
    environment:
      HOST: $HOST
    command: python manage.py bot
    depends_on:
      - web

  rabbitmq:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    restart: always
    image: mathwave/sprint-repo:sprint
    privileged: true
    command: scripts/create_worker.sh
    environment:
      SOLUTIONS_ROOT_EXTERNAL: "${SOLUTIONS_ROOT_EXTERNAL}"
      HOST: $HOST
    depends_on:
      - web
      - rabbitmq
      - postgres
      - storage
    volumes:
      - /sprint-data/worker:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock