# Generated by Django 3.2.4 on 2021-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211120_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
