# Generated by Django 3.2.4 on 2021-12-07 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_settask_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='editors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
