# Generated by Django 3.0.2 on 2020-06-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_solution_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.UserInfo'),
        ),
    ]
