# Generated by Django 3.2.4 on 2021-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_task_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='test',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
