# Generated by Django 3.0.2 on 2020-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200629_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mark_notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='new_block_notification',
            field=models.IntegerField(default=0),
        ),
    ]
