# Generated by Django 3.2.4 on 2021-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='notification_friends',
            field=models.BooleanField(default=False),
        ),
    ]
