# Generated by Django 3.0.2 on 2020-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200702_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
