# Generated by Django 3.2.4 on 2021-12-23 12:36

import Main.models.userinfo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20211219_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(default='', max_length=30),
        ),
    ]
