# Generated by Django 3.0.2 on 2020-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
