# Generated by Django 3.2.4 on 2022-01-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_remove_userinfo_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extrafile',
            index=models.Index(fields=['task'], name='Main_extraf_task_id_423651_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user'], name='Main_friend_from_us_0923c9_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['to_user'], name='Main_friend_to_user_389a97_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-time_sent'], name='Main_messag_chat_id_494037_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'task'], name='Main_progre_user_id_3ed604_idx'),
        ),
        migrations.AddIndex(
            model_name='settask',
            index=models.Index(fields=['set'], name='Main_settas_set_id_046a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['task', 'user', '-time_sent'], name='Main_soluti_task_id_0d9c15_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['task', '-time_sent'], name='Main_soluti_task_id_878836_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionfile',
            index=models.Index(fields=['solution'], name='Main_soluti_solutio_cebd76_idx'),
        ),
    ]
