# Generated by Django 3.1 on 2020-09-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20200901_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraFile',
        ),
    ]
