# Generated by Django 3.2.4 on 2022-01-20 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20220120_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='editors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
