# Generated by Django 3.2.4 on 2022-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_set_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
