# Generated by Django 3.2.4 on 2022-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20220120_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
