# Generated by Django 3.2.4 on 2022-01-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_set_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
