# Generated by Django 3.1 on 2020-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_task_max_solutions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
