# Generated by Django 3.2.4 on 2022-02-11 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20220201_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
