# Generated by Django 3.1 on 2020-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_remove_extrafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_details',
            field=models.IntegerField(default=1),
        ),
    ]
