# Generated by Django 3.1 on 2020-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_task_show_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution_type',
            field=models.TextField(default='Решение'),
        ),
    ]
