# Generated by Django 3.1 on 2020-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_remove_task_solution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_solution',
            field=models.IntegerField(default=0),
        ),
    ]
