# Generated by Django 3.2.4 on 2022-02-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20220215_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
