# Generated by Django 3.1 on 2020-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_task_full_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafile',
            name='for_compilation',
            field=models.IntegerField(default=0),
        ),
    ]
