# Generated by Django 3.1 on 2020-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_extrafile_for_compilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafile',
            name='sample',
            field=models.IntegerField(default=0),
        ),
    ]
