# Generated by Django 3.2.4 on 2022-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_auto_20220225_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='extras',
            field=models.JSONField(default=dict),
        ),
    ]
