# Generated by Django 3.1 on 2020-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_extrafile_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mark_notification',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='new_block_notification',
        ),
        migrations.AlterField(
            model_name='block',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extrafile',
            name='for_compilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extrafile',
            name='sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='full_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='show_details',
            field=models.BooleanField(default=False),
        ),
    ]
