# Generated by Django 3.2.4 on 2022-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_alter_solution_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='access_token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
