# Generated by Django 3.1.3 on 2020-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20201106_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_rating',
            field=models.BooleanField(default=True),
        ),
    ]
