# Generated by Django 3.2.4 on 2022-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_group_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
