# Generated by Django 3.2.4 on 2022-03-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_dump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dump',
            name='ready',
        ),
    ]
