# Generated by Django 3.2.4 on 2022-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_remove_dump_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='changes',
            field=models.JSONField(default=list),
        ),
    ]
