# Generated by Django 3.2.4 on 2022-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_task_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='vk_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
