# Generated by Django 3.1.3 on 2021-03-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_block_cheating_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='cheating_data',
        ),
    ]
