# Generated by Django 3.2.4 on 2022-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20220408_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='docker_instances',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
