# Generated by Django 3.2.4 on 2022-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_solution_docker_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='docker_instances',
        ),
        migrations.AddField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(default=1024),
        ),
    ]
