# Generated by Django 3.2.4 on 2022-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20220509_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='memory_limit',
        ),
    ]
