# Generated by Django 3.2.5 on 2021-07-25 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Main", "0034_auto_20210725_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
