# Generated by Django 3.2.4 on 2022-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_task_memory_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telegram_chat_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
