# Generated by Django 3.2.5 on 2021-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0040_auto_20210803_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="profile_pictures"),
        ),
    ]
