# Generated by Django 3.2.5 on 2021-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0041_userinfo_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
