# Generated by Django 3.2.5 on 2021-08-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0044_settask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="users",
        ),
        migrations.RemoveField(
            model_name="set",
            name="tasks",
        ),
        migrations.AddField(
            model_name="group",
            name="sets",
            field=models.ManyToManyField(to="Main.Set"),
        ),
        migrations.AddField(
            model_name="set",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="settask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settasks",
                to="Main.task",
            ),
        ),
    ]
