# Generated by Django 3.2.5 on 2021-08-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0045_auto_20210803_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="Main.group",
            ),
        ),
    ]
