# Generated by Django 3.2.5 on 2021-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
