# Generated by Django 3.2.5 on 2021-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0050_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_type',
            field=models.TextField(null=True),
        ),
    ]
