# Generated by Django 3.2.5 on 2021-08-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0051_language_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
