# Generated by Django 3.2.5 on 2021-08-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0052_language_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
