# Generated by Django 3.2.5 on 2021-08-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0055_extrafile_readable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafile',
            name='file',
        ),
    ]
