# Generated by Django 3.2.5 on 2021-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0056_remove_extrafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafile',
            name='is_test',
            field=models.BooleanField(null=True),
        ),
    ]
