# Generated by Django 3.2.5 on 2021-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0058_extrafile_test_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.TextField(default='ubuntu'),
        ),
    ]
