# Generated by Django 3.2.4 on 2021-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0060_language_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafile',
            name='is_sample',
            field=models.BooleanField(null=True),
        ),
    ]
