# Generated by Django 3.2.4 on 2021-09-01 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0062_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
