# Generated by Django 3.2.4 on 2021-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0063_alter_progress_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rating',
        ),
        migrations.AddField(
            model_name='progress',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
