# Generated by Django 3.2.4 on 2021-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0064_auto_20210901_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_estimation',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
