# Generated by Django 3.2.4 on 2021-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0065_auto_20210901_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
