# Generated by Django 3.2.4 on 2021-09-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0067_userinfo_notification_solution_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='telegram_chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
