# Generated by Django 3.2.4 on 2021-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0069_remove_userinfo_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='telegram_chat_id',
            field=models.TextField(default=''),
        ),
    ]
