# Generated by Django 3.2.4 on 2021-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0070_userinfo_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='highlight',
            field=models.TextField(default='nohighlight'),
        ),
    ]
