# Generated by Django 3.2.4 on 2021-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0071_language_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='highlight',
            field=models.TextField(default='plaintext'),
        ),
    ]
