# Generated by Django 3.2.4 on 2021-11-05 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0072_alter_language_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='set',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
