# Generated by Django 3.2.4 on 2021-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0073_auto_20211106_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='language',
        ),
        migrations.AddField(
            model_name='solution',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
    ]
