# Generated by Django 3.2.4 on 2021-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0075_auto_20211110_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture_fs_id',
            field=models.IntegerField(null=True),
        ),
    ]
