# Generated by Django 3.2.4 on 2022-02-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_alter_chat_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
