# Generated by Django 3.2.4 on 2022-02-15 18:22

import Checker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0020_languageapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=Checker.models.generate_token, max_length=30)),
                ('last_request', models.DateTimeField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.set')),
                ('testing_solution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.solution')),
            ],
        ),
    ]
