# Generated by Django 3.2.4 on 2022-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0002_alter_checker_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
