# Generated by Django 3.2.4 on 2022-02-15 18:48

import Checker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0003_checker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='token',
            field=models.CharField(db_index=True, default=Checker.models.generate_token, max_length=30, unique=True),
        ),
    ]
